name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build VRS on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04,  macOS-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"

      - name: Install dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update -y
            sudo apt-get upgrade -y
            sudo apt-get install -o Acquire::Retries=5 \
              cmake ninja-build ccache libgtest-dev libfmt-dev libcereal-dev \
              libturbojpeg-dev libpng-dev \
              liblz4-dev libzstd-dev libxxhash-dev \
              libboost-system-dev libboost-filesystem-dev libboost-thread-dev libboost-chrono-dev libboost-date-time-dev \
              portaudio19-dev
            python -m pip install -U pip
            python -m pip install pybind11[global]

          elif [ "$RUNNER_OS" == "macOS" ]; then
              brew install ninja cmake ccache googletest glog fmt cereal \
                  jpeg-turbo libpng \
                  lz4 zstd xxhash \
                  boost \
                  portaudio pybind11

          else
              echo "$RUNNER_OS not supported"
              exit 1
          fi
          python -m pip install -U pip
          python -m pip install numpy typing dataclasses pytest parameterized Pillow

      - name: Build and Test Python
        shell: bash
        run: |
          rm -rf csrc/vrs/pyvrs
          pip install -e .
          python -m pytest test
